### ISSUE TITLE
Push mode?

### ISSUE THREAD

**Issue by andyl** [nats-io/ruby-nats-streaming#9]
With this gem, I can poll the `nats-streaming-server` for new messages.

But I haven't been able to figure out how to create a client that receives messages using server-push.

Is this possible?  Am I just missing something here?

**Comment by wallyqs** [comment]
Hi @andyl, I'm sorry I'm not following. What do you mean by server-push? Could you share a bit more about the use case?

**Comment by andyl** [comment]
Thanks for your note @wallyqs - I figured it out.  Have some sample scripts that might be useful to others - will submit a PR for you shortly...
